# Путь до .txt файла с образцами команд для построения модели с комментариями (их нельзя скармливать опере)
path = r"C:\Users\Mi\Desktop\opera_proj\образец скриптов\логи_моделер.txt"

# Путь до .comi файла с образцами команд для построения модели без комментариев (они скармливаются опере)
path_load = r"C:\Users\Mi\Desktop\opera_proj\образец скриптов\check.comi"

# Путь до .txt файла с образцами команд для расчетов модели с комментариями (их нельзя скармливать опере)
path_post = r"C:\Users\Mi\Desktop\opera_proj\образец скриптов\логи_пост_процессор.txt"

# Путь до .comi файла с образцами команд для расчетов модели без комментариев (они скармливаются опере)
path_post_load = r"C:\Users\Mi\Desktop\opera_proj\образец скриптов\check_post.comi"



# Путь до .csv файла для сохранения параметров формы
path_to_load_shape = r"C:\Users\Mi\Desktop\opera_proj\shape.csv"

# Путь до .csv файла для сохранения гармоник поля
path_grad_csv = r'C:\Users\Mi\Desktop\opera_proj\gradients.csv'


# Путь до папки, где будут лежать все скрипты .comi для оперы. Необходимо добавить \... чтобы создавались файлы .comi
path_to_load_scripts = r"C:\Users\Mi\Desktop\opera_proj\скрипты_параметров_фасок"

# Путь до папки, куда закинем конечное значение формы чтобы проверить
path_to_load_scripts_2_check = r"C:\Users\Mi\Desktop\opera_proj"

# Пути до .lp файла с произвольными цифрами в названии - логи расчетов оперы. Для работы необходима библиотека glob
path_pattern = r"C:\Users\Mi\Desktop\opera_proj\opera_logs\Post_*.lp"

# Путь до локальной папки где лежит текущий скрипт для построения формы
path_local_dir = r'C:\Users\Mi\Desktop\opera_proj\локальная_папка'

# Путь до папки с логами работы оперы для удаления оттуда файлов
path_to_opera_logs = r"C:\Users\Mi\Desktop\opera_proj\opera_logs"


# Сам скрипт
comi_script = f'''
PREVIEW OPTION=PICK | PICK OPTION=ADD PROPERTY=UniqueName LABEL='ModelBody'
PREVIEW OPTION=ACCEPT REDISPLAY=NO |  DELETE REGULARISE=YES EXTERNAL=NO

PICK OPTION=ALL TYPE=CONDUCTOR
DELETE REGULARISE=YES EXTERNAL=NO

PICK OPTION=ALL TYPE=BODY
DELETE REGULARISE=YES EXTERNAL=NO

SKETCH OBJECT=BLOCK +COMPLETE
PREVIEW OPTION=START REDISPLAY=NO | BLOCK Name='Block' X0=-20 Y0=-10 Z0=10 X1=20 Y1=10 Z1=80
PREVIEW OPTION=END REDISPLAY=NO |  BLOCK Name='Block' X0=-20 Y0=-10 Z0=10 X1=20 Y1=10 Z1=80

PICK OPTION=TOGGLE TYPE=EDGE UNIQUEBODYNAME='Block' IDENTIFIER=A.00007
PICK OPTION=TOGGLE TYPE=EDGE UNIQUEBODYNAME='Block' IDENTIFIER=A.00005
PREVIEW OPTION=START REDISPLAY=NO | BLEND OPTION=CHAMFER LEFTCHAMFER=5 RIGHTCHAMFER=7
PREVIEW OPTION=END REDISPLAY=NO |  BLEND  OPTION=CHAMFER LEFTCHAMFER=5 RIGHTCHAMFER=7



PREVIEW OPTION=PICK | PICK OPTION=ADD PROPERTY=UniqueName LABEL='Block'
PREVIEW OPTION=ACCEPT REDISPLAY=NO |  CELLDATA OPTION=MODIFY MATERIALLABEL='Pec' POTENTIAL=Total ELEMENTTYPE=Quadratic LEVEL=20 SIZE=3 ELEMSHAPEPREF=NONE

MATERIALS GUIINIT
MATERIALS PICK 'Pec'
MATERIALS OPTION=MODIFY MULINEARITY=NONLINEAR MUANISOTROPY=ISOTROPIC BH='1010'

SKETCH OBJECT=CYLINDER +COMPLETE
PREVIEW OPTION=START REDISPLAY=NO | CYLINDER Name='Cylinder-001' X0=0 Y0=-20 Z0=0 X1=0 Y1=20 Z1=0 -TUBE SHAPECONTROL=SIMPLE MAJORRADIUS=30 MINORRADIUS=30 TOPRADIUS=30 SIDES=2
PREVIEW OPTION=END REDISPLAY=NO |  CYLINDER Name='Cylinder-001' X0=0 Y0=-20 Z0=0 X1=0 Y1=20 Z1=0 -TUBE SHAPECONTROL=SIMPLE MAJORRADIUS=30 MINORRADIUS=30 TOPRADIUS=30 SIDES=2
PREVIEW OPTION=PICK | PICK OPTION=ADD PROPERTY=UniqueName LABEL='Cylinder-001'
PREVIEW OPTION=ACCEPT REDISPLAY=NO |  CELLDATA OPTION=MODIFY MATERIALLABEL='Air' POTENTIAL=Default ELEMENTTYPE=Quadratic LEVEL=5 SIZE=3 ELEMSHAPEPREF=NONE

RACETRACK OPTION=LOAD
RACETRACK OPTION=NEW -KEEP XP1=10 YP1=20 WIDTH=5 THICKNESS=40 H1=15 R1=5 INCIRCUIT=NO CIRCUITELEMENT= CURD=10 TOLERANCE=0 DRIVELABEL='Default Drive' THETA2=90 PHI2=0 PSI2=90 XCEN2=0 YCEN2=0 ZCEN2=0 LCNAME='Global coordinate system' RXY=0 RYZ=0 RZX=0 SYMMETRY=1 MODELCOMPONENT=NO

FILTER COMMAND=PICK
FILTER TYPE=EDGE
PICK OPTION=TOGGLE TYPE=EDGE UNIQUEBODYNAME='Block' IDENTIFIER=A.00009
PICK OPTION=TOGGLE TYPE=EDGE UNIQUEBODYNAME='Block' IDENTIFIER=A.00010
PICK OPTION=TOGGLE TYPE=EDGE UNIQUEBODYNAME='Block' IDENTIFIER=A.00012
PICK OPTION=TOGGLE TYPE=EDGE UNIQUEBODYNAME='Block' IDENTIFIER=A.00011
PREVIEW OPTION=PICK | PICK OPTION=ADD TYPE=EDGE UNIQUEBODYNAME='Block' IDENTIFIER=A.00011
PREVIEW OPTION=START REDISPLAY=NO | BLEND OPTION=BLEND RADIUS=5
PREVIEW OPTION=ACCEPT REDISPLAY=NO |  BLEND  OPTION=BLEND RADIUS=5

PICK OPTION=TOGGLE PROPERTY=UniqueName LABEL='Block'
FILTER TYPE=CONDUCTOR
PICK OPTION=TOGGLE TYPE=COND N=1
PREVIEW OPTION=PICK | PICK OPTION=ADD TYPE=COND N=1
PREVIEW OPTION=START REDISPLAY=NO | TRANSFORM OPTION=APPLY TYPE=DISPLACE DU=0 DV=0 DW=20
PREVIEW OPTION=ACCEPT REDISPLAY=NO |   TRANSFORM OPTION=APPLY KEEP=NO TYPE=DISPLACE DU=0 DV=0 DW=20

SELECT OPTION=DEFAULT
SKETCH OBJECT=CYLINDER +COMPLETE
PREVIEW OPTION=END REDISPLAY=NO |  CYLINDER Name='Cylinder-002' X0=0 Y0=-50 Z0=0 X1=0 Y1=50 Z1=0 -TUBE SHAPECONTROL=SIMPLE MAJORRADIUS=180 MINORRADIUS=180 TOPRADIUS=180 SIDES=2
FILTER COMMAND=CURSORHIDE
FILTER TYPE=BODY
SELECT OPTION=CURSORHIDE PROPERTY=UniqueName LABEL='Cylinder-002'

SELECT OPTION=DEFAULT
PREVIEW OPTION=PICK | PICK OPTION=ADD PROPERTY=UniqueName LABEL='Cylinder-002'
PREVIEW OPTION=ACCEPT REDISPLAY=NO |  CELLDATA OPTION=MODIFY MATERIALLABEL='Air' POTENTIAL=Default ELEMENTTYPE=Quadratic LEVEL=1 ELEMSHAPEPREF=NONE
PREVIEW OPTION=PICK | PICK OPTION=ADD PROPERTY=UniqueName LABEL='Cylinder-002'
PREVIEW OPTION=ACCEPT REDISPLAY=NO |  RENAME NAME=Background UNIQUENAME=
SELECT OPTION=CURSORHIDE PROPERTY=UniqueName LABEL='Cylinder-002'

SKETCH OBJECT=CYLINDER +COMPLETE
PREVIEW OPTION=START REDISPLAY=NO | CYLINDER Name='Magnitoprovod' X0=0 Y0=-10 Z0=0 X1=0 Y1=10 Z1=0 +TUBE SHAPECONTROL=TUBE MAJORRADIUS=120 MINORRADIUS=120 TOPRADIUS=120 THICKNESS=30 SIDES=2 MATERIALLABEL='Pec' LEVEL=20
PREVIEW OPTION=END REDISPLAY=NO |  CYLINDER Name='Magnitoprovod' X0=0 Y0=-10 Z0=0 X1=0 Y1=10 Z1=0 +TUBE SHAPECONTROL=TUBE MAJORRADIUS=120 MINORRADIUS=120 TOPRADIUS=120 THICKNESS=30 SIDES=2 MATERIALLABEL='Pec' LEVEL=20
PREVIEW OPTION=PICK | PICK OPTION=ADD PROPERTY=UniqueName LABEL='Magnitoprovod'
PREVIEW OPTION=ACCEPT REDISPLAY=NO |  CELLDATA OPTION=MODIFY MATERIALLABEL='Pec' POTENTIAL=Total ELEMENTTYPE=Quadratic LEVEL=20 ELEMSHAPEPREF=NONE

FILTER TYPE=BODY
PICK OPTION=TOGGLE PROPERTY=UniqueName LABEL='Block'
FILTER TYPE=CONDUCTOR
PICK OPTION=TOGGLE TYPE=COND N=1
PREVIEW OPTION=PICK | PICK OPTION=ADD TYPE=COND N=1
PREVIEW OPTION=START REDISPLAY=NO | TRANSFORM OPTION=APPLY TYPE=ROTATE ROTU=0 ROTV=1 ROTW=0 ANGLE=45
PREVIEW OPTION=ACCEPT REDISPLAY=NO |   TRANSFORM OPTION=APPLY KEEP=NO TYPE=ROTATE ROTU=0 ROTV=1 ROTW=0 ANGLE=45


SKETCH OBJECT=BLOCK +COMPLETE
PREVIEW OPTION=START REDISPLAY=NO | BLOCK Name='Block1' X0=-20 Y0=-10 Z0=10 X1=20 Y1=10 Z1=80
PREVIEW OPTION=END REDISPLAY=NO |  BLOCK Name='Block1' X0=-20 Y0=-10 Z0=10 X1=20 Y1=10 Z1=80
PICK OPTION=TOGGLE TYPE=EDGE UNIQUEBODYNAME='Block1' IDENTIFIER=A.00007
PICK OPTION=TOGGLE TYPE=EDGE UNIQUEBODYNAME='Block1' IDENTIFIER=A.00005
PREVIEW OPTION=START REDISPLAY=NO | BLEND OPTION=CHAMFER LEFTCHAMFER=5 RIGHTCHAMFER=7
PREVIEW OPTION=END REDISPLAY=NO |  BLEND  OPTION=CHAMFER LEFTCHAMFER=5 RIGHTCHAMFER=7
PREVIEW OPTION=PICK | PICK OPTION=ADD PROPERTY=UniqueName LABEL='Block1'
PREVIEW OPTION=ACCEPT REDISPLAY=NO |  CELLDATA OPTION=MODIFY MATERIALLABEL='Pec' POTENTIAL=Total ELEMENTTYPE=Quadratic LEVEL=20 SIZE=3 ELEMSHAPEPREF=NONE
FILTER COMMAND=CURSORHIDE
FILTER COMMAND=PICK
FILTER TYPE=EDGE
PICK OPTION=TOGGLE TYPE=EDGE UNIQUEBODYNAME='Block1' IDENTIFIER=A.00009
PICK OPTION=TOGGLE TYPE=EDGE UNIQUEBODYNAME='Block1' IDENTIFIER=A.00010
PICK OPTION=TOGGLE TYPE=EDGE UNIQUEBODYNAME='Block1' IDENTIFIER=A.00012
PICK OPTION=TOGGLE TYPE=EDGE UNIQUEBODYNAME='Block1' IDENTIFIER=A.00011
PREVIEW OPTION=PICK | PICK OPTION=ADD TYPE=EDGE UNIQUEBODYNAME='Block1' IDENTIFIER=A.00011
PREVIEW OPTION=START REDISPLAY=NO | BLEND OPTION=BLEND RADIUS=5
PREVIEW OPTION=ACCEPT REDISPLAY=NO |  BLEND  OPTION=BLEND RADIUS=5
PICK OPTION=TOGGLE PROPERTY=UniqueName LABEL='Block1'
PREVIEW OPTION=START REDISPLAY=NO | TRANSFORM OPTION=APPLY TYPE=DISPLACE DU=0 DV=0 DW=20
PREVIEW OPTION=ACCEPT REDISPLAY=NO |   TRANSFORM OPTION=APPLY KEEP=NO TYPE=DISPLACE DU=0 DV=0 DW=20
FILTER TYPE=BODY
PICK OPTION=TOGGLE PROPERTY=UniqueName LABEL='Block1'
PREVIEW OPTION=START REDISPLAY=NO | TRANSFORM OPTION=APPLY TYPE=ROTATE ROTU=0 ROTV=1 ROTW=0 ANGLE=135
PREVIEW OPTION=ACCEPT REDISPLAY=NO |   TRANSFORM OPTION=APPLY KEEP=NO TYPE=ROTATE ROTU=0 ROTV=1 ROTW=0 ANGLE=135

SKETCH OBJECT=BLOCK +COMPLETE
PREVIEW OPTION=START REDISPLAY=NO | BLOCK Name='Block2' X0=-20 Y0=-10 Z0=10 X1=20 Y1=10 Z1=80
PREVIEW OPTION=END REDISPLAY=NO |  BLOCK Name='Block2' X0=-20 Y0=-10 Z0=10 X1=20 Y1=10 Z1=80
PICK OPTION=TOGGLE TYPE=EDGE UNIQUEBODYNAME='Block2' IDENTIFIER=A.00007
PICK OPTION=TOGGLE TYPE=EDGE UNIQUEBODYNAME='Block2' IDENTIFIER=A.00005
PREVIEW OPTION=START REDISPLAY=NO | BLEND OPTION=CHAMFER LEFTCHAMFER=5 RIGHTCHAMFER=7
PREVIEW OPTION=END REDISPLAY=NO |  BLEND  OPTION=CHAMFER LEFTCHAMFER=5 RIGHTCHAMFER=7
PREVIEW OPTION=PICK | PICK OPTION=ADD PROPERTY=UniqueName LABEL='Block2'
PREVIEW OPTION=ACCEPT REDISPLAY=NO |  CELLDATA OPTION=MODIFY MATERIALLABEL='Pec' POTENTIAL=Total ELEMENTTYPE=Quadratic LEVEL=20 SIZE=3 ELEMSHAPEPREF=NONE
FILTER COMMAND=CURSORHIDE
FILTER COMMAND=PICK
FILTER TYPE=EDGE
PICK OPTION=TOGGLE TYPE=EDGE UNIQUEBODYNAME='Block2' IDENTIFIER=A.00009
PICK OPTION=TOGGLE TYPE=EDGE UNIQUEBODYNAME='Block2' IDENTIFIER=A.00010
PICK OPTION=TOGGLE TYPE=EDGE UNIQUEBODYNAME='Block2' IDENTIFIER=A.00012
PICK OPTION=TOGGLE TYPE=EDGE UNIQUEBODYNAME='Block2' IDENTIFIER=A.00011
PREVIEW OPTION=PICK | PICK OPTION=ADD TYPE=EDGE UNIQUEBODYNAME='Block2' IDENTIFIER=A.00011
PREVIEW OPTION=START REDISPLAY=NO | BLEND OPTION=BLEND RADIUS=5
PREVIEW OPTION=ACCEPT REDISPLAY=NO |  BLEND  OPTION=BLEND RADIUS=5
PICK OPTION=TOGGLE PROPERTY=UniqueName LABEL='Block2'
PREVIEW OPTION=START REDISPLAY=NO | TRANSFORM OPTION=APPLY TYPE=DISPLACE DU=0 DV=0 DW=20
PREVIEW OPTION=ACCEPT REDISPLAY=NO |   TRANSFORM OPTION=APPLY KEEP=NO TYPE=DISPLACE DU=0 DV=0 DW=20
FILTER TYPE=BODY
PICK OPTION=TOGGLE PROPERTY=UniqueName LABEL='Block2'
PREVIEW OPTION=START REDISPLAY=NO | TRANSFORM OPTION=APPLY TYPE=ROTATE ROTU=0 ROTV=1 ROTW=0 ANGLE=225
PREVIEW OPTION=ACCEPT REDISPLAY=NO |   TRANSFORM OPTION=APPLY KEEP=NO TYPE=ROTATE ROTU=0 ROTV=1 ROTW=0 ANGLE=225

SKETCH OBJECT=BLOCK +COMPLETE
PREVIEW OPTION=START REDISPLAY=NO | BLOCK Name='Block3' X0=-20 Y0=-10 Z0=10 X1=20 Y1=10 Z1=80
PREVIEW OPTION=END REDISPLAY=NO |  BLOCK Name='Block3' X0=-20 Y0=-10 Z0=10 X1=20 Y1=10 Z1=80
PICK OPTION=TOGGLE TYPE=EDGE UNIQUEBODYNAME='Block3' IDENTIFIER=A.00007
PICK OPTION=TOGGLE TYPE=EDGE UNIQUEBODYNAME='Block3' IDENTIFIER=A.00005
PREVIEW OPTION=START REDISPLAY=NO | BLEND OPTION=CHAMFER LEFTCHAMFER=5 RIGHTCHAMFER=7
PREVIEW OPTION=END REDISPLAY=NO |  BLEND  OPTION=CHAMFER LEFTCHAMFER=5 RIGHTCHAMFER=7
PREVIEW OPTION=PICK | PICK OPTION=ADD PROPERTY=UniqueName LABEL='Block3'
PREVIEW OPTION=ACCEPT REDISPLAY=NO |  CELLDATA OPTION=MODIFY MATERIALLABEL='Pec' POTENTIAL=Total ELEMENTTYPE=Quadratic LEVEL=20 SIZE=3 ELEMSHAPEPREF=NONE
FILTER COMMAND=CURSORHIDE
FILTER COMMAND=PICK
FILTER TYPE=EDGE
PICK OPTION=TOGGLE TYPE=EDGE UNIQUEBODYNAME='Block3' IDENTIFIER=A.00009
PICK OPTION=TOGGLE TYPE=EDGE UNIQUEBODYNAME='Block3' IDENTIFIER=A.00010
PICK OPTION=TOGGLE TYPE=EDGE UNIQUEBODYNAME='Block3' IDENTIFIER=A.00012
PICK OPTION=TOGGLE TYPE=EDGE UNIQUEBODYNAME='Block3' IDENTIFIER=A.00011
PREVIEW OPTION=PICK | PICK OPTION=ADD TYPE=EDGE UNIQUEBODYNAME='Block3' IDENTIFIER=A.00011
PREVIEW OPTION=START REDISPLAY=NO | BLEND OPTION=BLEND RADIUS=5
PREVIEW OPTION=ACCEPT REDISPLAY=NO |  BLEND  OPTION=BLEND RADIUS=5
PICK OPTION=TOGGLE PROPERTY=UniqueName LABEL='Block3'
PREVIEW OPTION=START REDISPLAY=NO | TRANSFORM OPTION=APPLY TYPE=DISPLACE DU=0 DV=0 DW=20
PREVIEW OPTION=ACCEPT REDISPLAY=NO |   TRANSFORM OPTION=APPLY KEEP=NO TYPE=DISPLACE DU=0 DV=0 DW=20
FILTER TYPE=BODY
PICK OPTION=TOGGLE PROPERTY=UniqueName LABEL='Block3'
PREVIEW OPTION=START REDISPLAY=NO | TRANSFORM OPTION=APPLY TYPE=ROTATE ROTU=0 ROTV=1 ROTW=0 ANGLE=315
PREVIEW OPTION=ACCEPT REDISPLAY=NO |   TRANSFORM OPTION=APPLY KEEP=NO TYPE=ROTATE ROTU=0 ROTV=1 ROTW=0 ANGLE=315

PICK OPTION=TOGGLE PROPERTY=UniqueName LABEL='Magnitoprovod'
PICK OPTION=TOGGLE PROPERTY=UniqueName LABEL='Block2'
PICK OPTION=TOGGLE PROPERTY=UniqueName LABEL='Block3'
PICK OPTION=TOGGLE PROPERTY=UniqueName LABEL='Block1'
PICK OPTION=TOGGLE PROPERTY=UniqueName LABEL='Block'
PREVIEW OPTION=PICK | PICK OPTION=ADD PROPERTY=UniqueName LABEL='Magnitoprovod'
PREVIEW OPTION=ACCEPT REDISPLAY=NO |  COMBINE OPERATION=UNION +REGULAR

PICK OPTION=TOGGLE PROPERTY=UniqueName LABEL='Magnitoprovod'
PICK OPTION=TOGGLE PROPERTY=UniqueName LABEL='Cylinder-001'
PICK OPTION=TOGGLE PROPERTY=UniqueName LABEL='Cylinder-002'
FILTER TYPE=CONDUCTOR
PICK OPTION=TOGGLE TYPE=COND N=1
PREVIEW OPTION=END REDISPLAY=NO |   TRANSFORM OPTION=APPLY KEEP=NO TYPE=ROTATE ROTU=1 ROTV=0 ROTW=0 ANGLE=90

PREVIEW OPTION=PICK | PICK OPTION=ADD TYPE=COND N=1
RACETRACK OPTION=LOAD
PREVIEW OPTION=ACCEPT REDISPLAY=NO |  RACETRACK OPTION=MODIFY -KEEP XP1=10 YP1=20 WIDTH=5 THICKNESS=40 H1=15 R1=5 INCIRCUIT=NO CIRCUITELEMENT= CURD=10 TOLERANCE=0 DRIVELABEL='Default Drive' LCNAME='Global coordinate system' XCEN2=14.1421356237309 YCEN2=-14.1421356237309 ZCEN2=8.65956056235493E-16 THETA2=90 PHI2=45 PSI2=180 RXY=0 RYZ=0 RZX=0 SYMMETRY=-4 MODELCOMPONENT=NO

ANALYSISDATA OPTION=LOAD PROGRAM=TOSCAMAGN
ANALYSISDATA OPTION=SET PROGRAM=TOSCAMAGN LINEAR=NO NLITERTYPE=NEWTON NITERATIONS=50 TOLERANCE=1.0E-05 HX=0 HY=0 HZ=0 RHS=ADAPTIVE POTENTIALCUT=YES

BACKGROUND OPTION=LOAD
BACKGROUND OPTION=SET SHAPE=CYLINDER SCALEZ=5 SCALER=3   XYSYMMETRYPLANE=YES YZSYMMETRYPLANE=NO ZXSYMMETRYPLANE=YES EMRXY=TANGMAGN EMRZX=NORMMAGN ROTZNUM=4 EMROTZTYPE=TANGMAGN

BHDATA OPTION=EDIT  label=1010
BHDATA OPTION=LOAD LABEL=1010 FILE='C:/Program Files/Vector Fields/Opera 15R3 x64/bh/tenten.bh'

MODEL CREATE

MESH SIZE=50.0 NORMALTOL=30.0 SURFACETOL=0.0 TOLERANCE=1.0E-06 TYPE=PREFERTETRA

FILL TOL=1.0E-06

SOLVERS SOLVENOW=YES SAVEMODEL=YES, | SOLVERS OPTION=TEST FILE='quadrupol1' UNITS=MM ELEMENT=MIXED SURFACE=CURVED, | COMMENT CLEAR=YES TYPE=DBTITLE, | SOLVERS OPTION=OVERWRITE
'''